- name: Post-provision config and validation
  hosts: new_vm
  gather_facts: true
  tasks:
    - block:
        - ansible.builtin.wait_for_connection:
            timeout: 300
        - ansible.builtin.ping:
      rescue:
        - servicenow.itsm.incident:
            instance:
              host: "{{ SN_HOST }}"
              username: "{{ SN_USERNAME }}"
              password: "{{ SN_PASSWORD }}"
            short_description: "Demo: VM not reachable after provisioning: {{ vm_name }}"
            description: |
              VM provisioned but not reachable via SSH.

              VM: {{ vm_name }}
              Namespace: {{ vm_namespace }}
              IP: {{ hostvars['localhost']['vm_ip'] | default('unknown') }}
              AAP Job ID: {{ tower_job_id | default('unknown') }}
            state: new
          delegate_to: localhost
        - ansible.builtin.fail:
            msg: "Validation failed; incident created."