- name: Create a basic rhel vm
  hosts: all
  gather_facts: true

  tasks:
    - name: Create a VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        labels:
          app: test
        instancetype:
          name: "{{ vm_instance_type }}"
        preference:
          name: "{{ vm_preference_os }}"
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  masquerade: {}
              disks:
                - name: rootdisk
                  disk:
                    bus: virtio
          networks:
            - name: default
              pod: {}
          dataVolumeTemplates:
            - metadata:
                name: rootdisk
              spec:
                sourceRef:
                  kind: DataSource
                  name: rhel9
                  namespace: openshift-virtualization-os-images
                storage:
                  resources:
                    requests:
                      storage: 30Gi    # or whatever size you want
                  accessModes:
                    - ReadWriteOnce
        running: true
