---
- name: Create a change request to trigger EDA Polling
  hosts: all
  gather_facts: true

  tasks:
    - name: Create a new incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: "{{ SN_USERNAME }}"
        short_description: User is not receiving email
        description: User has been unable to receive email for the past 15 minutes
        impact: low
        urgency: low
