- name: Watch for new records
  hosts: all
  sources:
  
    - name: Watch for records using sys_created_on
      servicenow.itsm.records:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        table: incident
        remote_servicenow_timezone: UTC
        timestamp_field: sys_created_on
        interval: 10

  rules:
    - name: New record created
      condition: event.sys_id is defined
      action:
        run_job_template:
          name: "{{ jobTemplate }}"
          organization: "{{ org }}"
